### ISSUE TITLE
Fail to build with 2.9 on Fedora 36

### ISSUE THREAD

**Issue by ycollet** [reales/OB-Xd#72]
I try to build OB-Xd on Fedora 36.
The build fails with the following error:
```
../../Source/PluginProcessor.cpp: In function 'juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout()':
../../Source/PluginProcessor.cpp:43:13: error: 'ParameterID' was not declared in this scope; did you mean 'parameter'?
   43 |             ParameterID{ id, 1 }, name, range, defaultValue, String{}, AudioProcessorParameter::genericParameter,
      |             ^~~~~~~~~~~
      |             parameter
```

**Comment by plaimbock** [comment]
I had no problems building it on F36. Make sure you use JUCE-7.0.1 (see https://github.com/reales/OB-Xd#building). I built it with vst-sdk_3.7.5_build-44_2022-05-19.zip and vstsdk3610_11_06_2018_build_37.zip
