### ISSUE TITLE
Problem compiling v2.10 as LV2 using JUCE 7.0.2 (including fixes)

### ISSUE THREAD

**Issue by gitterdude** [reales/OB-Xd#77]
I have /usr/src/OB-Xd and /usr/src/JUCE folders

I run `../JUCE/Projucer  OB-Xd.jucer` from /usr/src/OB-Xd, set the JUCE global path to `/usr/src/JUCE` and the module path to ` /usr/src/JUCE/modules` , disable everything but LV2 and save the project.

Running ` make -j4 -C Builds/LinuxMakefile CONFIG=Release64` gives the error 
_../../Source/Components/../../JuceLibraryCode/JuceHeader.h:17:10: fatal error: juce_audio_basics/juce_audio_basics.h: File or folder not found
 #include <juce_audio_basics/juce_audio_basics.h>_

/usr/src/OB-Xd/Modules only contains a subset of the needed JUCE files for some reason so the workaround is to  run 
`rm -rf Modules/* && push Modules &&   ln -s ../../JUCE/modules/* .  && popd`

The second problem is that JUCE-7.0.2 still doesn't like pluginChannelConfigs, so prior to running Projucer it's necessary to run
`sed -i 's/pluginChannelConfigs="{.,.}"//' OB-Xd.jucer`

Tested in Ubuntu 18.04 and 22.04

**Comment by reales** [comment]
Not sure what the issue is. I can compile using Ubuntu 18.04 LTS just fine.

Does LV2 Linux binary has any issues? I thought JUCE fixed the the pluginChannelConfigs problems with 7.0.2 release.

**Comment by gitterdude** [comment]
The issue is that on can't just download JUCE, the OB-Xd source, run Projucer and run make without running into the _File or folder not found error_.
Or am I supposed to put the JUCE folder inside of the OB-Xd folder somewhere?
As explained in the initial post I've got them in separate folders, both right under /usr/src 

The pluginChannelConfigs problem is still there in 7.0.2. At least when running through PipeWire's Jack layer.
Removing pluginChannelConfigs="{2,0}" from OB-Xd.jucer makes it work again.

**Comment by reales** [comment]
Regarding the compilation, I’d recommend to ask at JUCE forums instead because it looks like an issue handling the framework.

A new Linux LV2 build will be ready without the channel config tomorrow for testing.

**Comment by gitterdude** [comment]
You wouldn't be kind enough to share how _you_ have it set up?

As far as configuring Projucer there's only the Global Paths to play around with, from what I can see, and I guess "Path to JUCE" should point to the folder containing Projucer and the "JUCE Modules" to the modules folder below that.
"User Modules" don't seem to matter wherever I point it.
I even tried to set the Header Search Paths in the Linux makefile exporter to /usr/src/JUCE/modules but got the same error.

With my workaround (linking or copying the JUCE/modules files to OB-Xd/Modules) you at least don't have to be a JUCE expert to be able to compile OB-Xd.

**Comment by reales** [comment]
I do appreciate the fix for channel config, however the JUCE setup is complex task, not really related to an issue with OB-Xd itself and at JUCE forums there are more qualified people for that purpose.

**Comment by gitterdude** [comment]
Well, at least people who only want to compile OB-Xd themselves can see this workaround, so they don't have to become JUCE experts first.

**Comment by reales** [comment]
The workaround is not really required If you know how to setup JUCE. Since this is not related to the application itself I'll open a new issue with the LV2 channel config issue and close this one.

**Comment by JamesFrederik** [comment]
> The issue is that on can't just download JUCE, the OB-Xd source, run Projucer and run make without running into the _File or folder not found error_. Or am I supposed to put the JUCE folder inside of the OB-Xd folder somewhere?

I have no idea either. I just wanted to change the path of the  presets folder from /Documents to /Home

I just threw the whole lot in the bin, PROJUCER can suck it.
